#' Get Titer from Fitted Model
#'
#' Extract the viral titer \emph{or} the volume required for one
#' infectious unit with confidence intervals from a fit object or
#' a list of fit objects generated by \code{\link{getFit}}.
#'
#' @param fm Fitted model or list of fitted models generated by
#' \code{\link{getFit}}.
#'
#' @param signif \code{Integer} number of significant digits to include
#'  with \code{getTiter} (default of 3)
#'
#' @return
#'
#' For \code{getTiter}, either a named numeric vector or matrix with the
#' estimated titer in IU per ml with +/- 95\% confidence intervals.
#'
#' @export
#'
getTiter <- function(fm, signif = 3)
{
	.fun <- function(fm) {
		units <- attr(fm, "unit")
		if (!units %in% c("ml", "ul", "nl", "pl"))
			warning("no 'unit' attribute found - titer may not be per ml")
		mult <- switch(units, ml = 1, ul = 1e3, nl = 1e6, pl = 1e9, 1)
		val <- signif(mult/getEC63(fm)[c(1,3,2)], signif)
	}
	if ("list" %in% class(fm))
		ret <- t(sapply(fm, .fun))
	else
		ret <- .fun(fm)
	return(ret)
}

#' @name getEC63
#' @rdname getTiter
#'
#' @return
#'
#' For \code{getEC63}, either a named numeric vector or matrix with the estimated
#' volume corresponding to 1 infectious unit with +/- 95\% confidence intervals.
#'
#' @export
#'
getEC63 <- function(fm)
{
	.coef <- function(fm) {
		cf <- numeric(3)
		if (is.null(fm))
			cf <- c(NA, NA, NA)
		else {
			cf[1] <- exp(-coef(fm))
			cfVal <- try(confint(fm))
			if(class(cfVal)[1] != "try-error")
				cf[c(3,2)] <- exp(-cfVal)
		}
		names(cf) <- c("est", "lo.CI", "hi.CI")
		cf
	}

	if ("list" %in% class(fm))
		ret <- t(sapply(fm, .coef))
	else
		ret <- .coef(fm)
	return(ret)
}

