#' Get Titer from Fitted Model
#'
#' Extract the viral titer \emph{aka} the volume required for one
#' infectious unit with confidence intervals from a fit object or
#' a list of fit objects generated by \code{\link{getFit}}.
#'
#' @param fm fitted model \emph{or} list of fitted models generated by
#'   \code{\link{getFit}}.
#' @param level this specifies the confidence level (default of 0.95).
#'   Use \code{NULL} to return only the titer (or EC63 value).
#' @param digits \code{Integer} number of significant digits to report
#'   (default = 2)
#' @param p probability (infected fraction) corresponding to an MOI of 1
#'	(default = 1 - exp(-1) = 0.6321)
#'
#' @return
#'
#' If \code{level} was provided, the return value includes the estimate and
#' confidence intervals. Note that the confidence interval reflects the
#' precision of the binomial fit is not necessarily \emph{biologically}
#' meaningful.
#'
#' @export
#'
getTiter <- function(fm, level = 0.95, digits = 2, p = 0.63212)
{
# option checks
  digits <- as.integer(digits[1])
  if (!is.null(level)) {
    level <- as.numeric(level)[1]
    if (level <= 0 | level >= 1)
      stop("'level' must be NULL or a single value between 0 and 1")
  }
	p <- as.numeric(p)[1]
	if (p <= 0 | p >= 1)
		stop("the prediction parameter 'p' must be between 0 and 1")

# working function
  warnUnits <- FALSE
  .fun <- function(fm, p, digits, level) {
    units <- attr(fm, "unit")
		if (is.null(units)) units <- "none"
    if (!units %in% c("ml", "ul", "nl", "pl")) warnUnits <<- TRUE
    mult <- switch(units, ml = 1, ul = 1e3, nl = 1e6, pl = 1e9, 1)
		x <- MASS::dose.p(fm, cf = 1:2, p = p)
		if (is.null(level))
			ans <- unname(mult/exp(as.numeric(x)))
		else {
			crit <- qnorm((1 - level)/2, lower.tail = FALSE) # estimate with normal
			xlo <- x - crit * attr(x, "SE")
			xhi <- x + crit * attr(x, "SE")
			ans <- signif(mult/exp(c(x, xhi, xlo)), digits)
			names(ans) <- c("est", "lo.CI", "hi.CI")
		}
		return(ans)
 }

# apply according to structure of 'fm'
	if (is(fm, "list"))
		ret <- t(sapply(fm, .fun, p, digits, level))
  else
		ret <- .fun(fm, p, digits, level)

# indicate units warning and return named vector or array
  if (warnUnits)
    warning("no volume attribute found in '", deparse(substitute(fm)), "'")
  return(drop(ret)) # remove uneeded dimensions
}
