#' Merge Phenotype and Image Data
#'
#' Merge "phenotype" data describing the samples in an image data.frame.
#'
#' @param phenoData A \code{data.frame} containing variables for the multiplicity,
#'   typically \code{moi} and either \code{well} or \code{file} associated with
#'   the unique multiplicity.
#' @param imageData A \code{data.frame} generated by \code{\link{parseImages}}.
#' @param moi Character name for multiplicity variable, either "moi" or "x".
#' @param stringsAsFactors Convert string variables to factors if \code{TRUE}
#'   (default value). Note that if present, \code{column} and \code{row} are
#'   preserved as factors regardless of this conversion.
#'
#' @details
#'
#' This function performs a \code{data.frame} merge with additional checks. It
#' does not (yet) respect the 'plate' variable and only merges according to the
#' \code{well} or \code{file} variables. For now, it is necessary to split
#' the phenoData and imageData by \code{plate}, merge each separately,
#' and then join the data back together. The following might work:
#'
#' \preformatted{
#'   g <- pd$plate
#'   pd <- split(pd, g)
#'   res <- split(res, res$plate)
#'   res <- Map(mergePdata, pd, res)
#'   res <- do.call(rbind, res)
#'   rownames(res) <- NULL
#'   pd <- unsplit(pd, g)
#' }
#'
#' @return
#'
#' Merged \code{data.frame} with harmonized well information (if appropriate)
#' and additional data provided in \code{phenoData}. The variables \code{row},
#' \code{column}, and \code{well} are expected to be factors. 
#'
#' @export
#'
mergePdata <- function(phenoData, imageData, moi = c("moi", "x"),
	stringsAsFactors = TRUE)
{
# intercept data with 'plate' present
	if ("plate" %in% names(phenoData) | "plate" %in% names(imageData)) {
		if (nlevels(factor(phenoData$plate)) > 1 | nlevels(factor(imageData$plate)) > 1)
			warning("see mergePdata() help to use 'plate' variable for merging")
	}
			
# process and check data according to the presence of "well"
	if ("well" %in% names(imageData) && !"well" %in% names(phenoData))
		stop("'well' found in ", deparse(substitute(imageData)),
			" but not in ", deparse(substitute(phenoData)))

	if ("well" %in% names(imageData)) {
	# process harmonized well value
		pdWell <- unique(well.info(phenoData$well)$well)
		idWell <- unique(well.info(imageData$well)$well)
		diffWell <- setdiff(idWell, pdWell)
		if (length(diffWell) != 0)
			stop(paste(diffWell, collapse = ", "), " are missing from ",
				deparse(substitute(phenoData)))

#	# process plate
#		pdPlate <- unique(phenoData$plate)
#		idPlate <- unique(imageData$plate)
#		diffPlate <- setdiff(idWell, pdWell)
#		if (length(diffPlate) != 0)
#			stop(paste(diffPlate, collapse = ", "), " are missing from ",
#				deparse(substitute(phenoData)))

	# replace (or add) harmonized row and column information to phenotype data
		phenoData$column <- well.info(phenoData$well)$column
		phenoData$row <- well.info(phenoData$well)$row

	# replace well names in phenodata with harmonized well names
		phenoData$well <- pdWell
	}
	else if ("file" %in% names(phenoData)) {
		if (!"file" %in% names(imageData))
			stop("A 'file' or 'well' variable must be present in ",
				deparse(substitute(imageData)))
	}

# check for 'unit' variable and assign if needed
	if (!"unit" %in% names(phenoData))
		phenoData$unit <- "[no unit]"

# check for 'type' variable and assign if needed
	if (!"type" %in% names(phenoData)) {
		type <- rep("standard", nrow(phenoData))
		if ("moi" %in% names(phenoData))
			type[phenoData$moi == 0] <- "control"
		else if ("x" %in% names(phenoData))
			type[phenoData$x == 0] <- "control"
		phenoData$type <- type
	}

# remove any variables in imageData that are present in phenoData EXCEPT
# for variables used to merge data frames: 'file' and/or 'well'
	vars <- names(imageData)[!names(imageData) %in% names(phenoData)]
	if ("file" %in% names(imageData)) vars <- c(vars, "file")
	if ("well" %in% names(imageData)) vars <- c(vars, "well")
	vars <- unique(vars)
	imageData <- imageData[vars]

# add temporary sorting variable for imageData and merge
	sval <- tail(make.unique(c(names(imageData), "srt")), 1)
	imageData[[sval]] <- seq_len(nrow(imageData))
	res <- merge(phenoData, imageData, all.y = TRUE) # Ugh...need all.y = TRUE
	ord <- order(res[[sval]])
	res <- res[ord, ]
	res <- res[names(res) != sval]

# convert strings to factors if requested
	if (stringsAsFactors == TRUE) {
		sel <- sapply(res, is.character)
		res[sel] <- lapply(res[sel], as.factor)
	}

# reorganize data
#	pdnames <- c("dir","file","plate","well","column","row","frame","type","unit")
	pdnames <- c("dir","file","well","column","row","frame","type","unit")
	first <- pdnames[pdnames %in% names(res)]
	last <- names(res)[!names(res) %in% pdnames]
	res <- res[c(first, last)]

# exclude unused levels (allows pd to hold more information than required)
	res <- droplevels(res)
	rownames(res) <- NULL
	return(res)
}
