#' Merge Phenotype and Image Data
#'
#' Merge "phenotype" data describing the samples in an image data.frame.
#'
#' @param phenoData A \code{data.frame} containing variables for the multiplicity,
#'   typically \code{moi} and either \code{well} or \code{file} associated with
#'   the unique multiplicity.
#' @param imageData A \code{data.frame} generated by \code{parseImages()}.
#' @param moi Character name for multiplicity variable, either "moi" or "x".
#'
#' @details
#'
#' This function performs a \code{data.frame} merge with additional checks.
#'
#' @return
#'
#' Merged \code{data.frame} with harmonized well information (if appropriate)
#' and additional data provided in \code{phenoData}.
#'
#' @export
#'
mergePdata <- function(phenoData, imageData, moi = c("moi", "x"))
{
# determine data type, check arguments and harmonize well names
#	if (!any(c("moi", "x") %in% names(phenoData)))
#		stop('"moi" or "x" must be in "phenoData"')
#
# for separate images in folders (multi-well)
	if ("well" %in% names(imageData)) {
		stopifnot("well" %in% names(phenoData))
		phenoData$well <- factor(well.info(phenoData$well)$well) # harmonize
		stopifnot(levels(imageData$well) %in% levels(phenoData$well))
	# add row and column information to phenotype data
		phenoData$column <- well.info(phenoData$well)$column
		phenoData$row <- well.info(phenoData$well)$row
	}
	else
		stopifnot("file" %in% names(phenoData))

# check value for unit and assign control wells
	if (!"unit" %in% names(phenoData))
		phenoData$unit <- "[no unit]"
	type <- rep("standard", nrow(phenoData))
	if ("moi" %in% names(phenoData))
		type[phenoData$moi == 0] <- "control"
	else if ("x" %in% names(phenoData))
		type[phenoData$x == 0] <- "control"
	phenoData$type <- type

# remove any variables in imageData that are present in phenoData EXCEPT
# for variables used to merge data frames: 'file' and/or 'well'
	vars <- names(imageData)[!names(imageData) %in% names(phenoData)]
	if ("file" %in% names(imageData)) vars <- c(vars, "file")
	if ("well" %in% names(imageData)) vars <- c(vars, "well")
	vars <- unique(vars)
	imageData <- imageData[vars]

# add temporary sorting variable for imageData and merge
	sval <- tail(make.unique(c(names(imageData), "srt")), 1)
	imageData[[sval]] <- seq_len(nrow(imageData))
	res <- merge(phenoData, imageData)
	ord <- order(res[[sval]])
	res <- res[ord, ]
	res <- res[names(res) != sval]

# convert strings to factors
	sel <- sapply(res, is.character)
	res[sel] <- lapply(res[sel], as.factor)

# reorganize data
	pdnames <- c("dir","file","column","row","well","frame","type","unit")
	first <- pdnames[pdnames %in% names(res)]
	last <- names(res)[!names(res) %in% pdnames]
	res <- res[c(first, last)]

# exclude unused levels (allows pd to hold information than required)
	res <- droplevels(res)
	rownames(res) <- NULL
	return(res)
}
